interface Vec2
{
    constructor(double x, double y);

    attribute double x;
    attribute double y;

    getter double (unsigned long index);
    setter void (unsigned long index, double value);

    double length();
    double lengthSquared();

	Vec2 normalize();
};