
//Generated by Cmake, TODO figure out how to get the automatic generation to work with dependents

#ifndef ACORN_EXPORT_H
#define ACORN_EXPORT_H

#ifdef ACORN_STATIC_DEFINE
	#define ACORN_EXPORT
	#define ACORN_NO_EXPORT
#else
	#ifndef ACORN_EXPORT
		#ifdef Acorn_EXPORTS
			/* We are building this library */
			#define ACORN_EXPORT __declspec(dllexport)
		#else
			/* We are using this library */
			#define ACORN_EXPORT __declspec(dllimport)
		#endif
	#endif

	#ifndef ACORN_NO_EXPORT
		#define ACORN_NO_EXPORT
	#endif
#endif

#ifndef ACORN_DEPRECATED
	#define ACORN_DEPRECATED __attribute__((__deprecated__))
#endif

#ifndef ACORN_DEPRECATED_EXPORT
	#define ACORN_DEPRECATED_EXPORT ACORN_EXPORT ACORN_DEPRECATED
#endif

#ifndef ACORN_DEPRECATED_NO_EXPORT
	#define ACORN_DEPRECATED_NO_EXPORT ACORN_NO_EXPORT ACORN_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
	#ifndef ACORN_NO_DEPRECATED
		#define ACORN_NO_DEPRECATED
	#endif
#endif

#endif /* ACORN_EXPORT_H */
